apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace

resources:
  - base/foo-deployment.yaml
  - base/bar-deployment.yaml

patches:
  - path: patches/add-env.yaml
    target:
      kind: Deployment
