apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-namespace

resources:
  - base/foo-deployment.yaml
  - base/bar-deployment.yaml

configMapGenerator:
- name: my-config
  envs:
  - my-env.env
